// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:nes_ticket/models/media_detail/media_detail_model.dart';
import 'package:nes_ticket/models/user/user_model.dart';
import 'package:nes_ticket/utils/enums/enums.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BelongsToCollectionAdapter());
    registerAdapter(GenreAdapter());
    registerAdapter(MediaDetailModelAdapter());
    registerAdapter(MediaTypeAdapter());
    registerAdapter(ProductionCompanyAdapter());
    registerAdapter(ProductionCountryAdapter());
    registerAdapter(SpokenLanguageAdapter());
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BelongsToCollectionAdapter());
    registerAdapter(GenreAdapter());
    registerAdapter(MediaDetailModelAdapter());
    registerAdapter(MediaTypeAdapter());
    registerAdapter(ProductionCompanyAdapter());
    registerAdapter(ProductionCountryAdapter());
    registerAdapter(SpokenLanguageAdapter());
    registerAdapter(UserModelAdapter());
  }
}
